-- AlterTable
ALTER TABLE "Media" ADD COLUMN     "seasonCount" INTEGER,
ALTER COLUMN "planets" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "starships" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "vehicles" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "species" SET DEFAULT ARRAY[]::TEXT[];
